-- =====================================================================================
-- 핵심 테이블 베이스라인 스키마 (users / subjects / schedules / user_timetables / wishlist_items)
-- =====================================================================================
--
-- [배경]
--   현재 db/migration 에는 위 핵심 테이블을 생성하는 CREATE TABLE 이 없다.
--   기존 운영 DB 는 과거 hibernate ddl-auto 가 만든 스키마 위에 baseline-on-migrate=true 로
--   증분 마이그레이션만 쌓아온 구조다. 따라서 "빈 DB"(신규 프로비저닝 / DR 복구 / 스테이징 검증 /
--   blue-green 신규 인스턴스용 DB)에서는 스키마를 코드로 재현할 수단이 없어 기동이 불가능하다.
--   이 파일은 그 공백을 메우기 위한 베이스라인 초안이다.
--
-- [경고 — 반드시 운영 스키마와 대조할 것]
--   이 스크립트는 JPA 엔티티(@Entity)에서 역산한 best-effort 초안이며, 실제 운영 스키마와
--   미묘하게 다를 수 있다(컬럼 길이/타입, 기본값, NOT NULL, 인덱스 이름, identity 전략 등).
--   네이밍은 Spring Boot 기본 물리 네이밍(camelCase -> snake_case)을 가정했다.
--   적용 전 반드시 운영 DB 의 정본 스키마와 대조하라:
--       pg_dump --schema-only --no-owner --no-privileges <DB> > prod_schema.sql
--   그리고 이 파일을 prod_schema.sql 로 교체하는 것이 가장 안전하다.
--
-- [Flyway 자동 적용 대상 아님]
--   spring.flyway.locations = classpath:db/migration 이므로 이 파일(db/baseline)은
--   애플리케이션 기동 시 자동 실행되지 않는다. 아래 절차에 따라 수동으로 사용한다.
--
-- ---------------------------------------------------------------------------------------
-- [시나리오 A] 기존 운영 DB 를 그대로 재사용해 재오픈
--   - 추가 작업 불필요. 현재 동작이 유지된다(스키마가 이미 존재).
--
-- [시나리오 B] 빈 DB 로 신규 구축 / DR 복구 / 스테이징 검증
--   1) 빈 DB 에 이 스크립트를 직접 실행해 핵심 테이블을 만든다.
--      (보조 테이블 user_majors / user_activity_daily / admin_audit_logs 는
--       db/migration 의 기존 마이그레이션이 생성하므로 여기 포함하지 않는다.)
--   2) 이 스키마는 "현재(최종) 엔티티 상태"를 반영하므로, 빈 DB 에서는 기존 증분 마이그레이션을
--      건너뛰도록 Flyway baseline 을 최신 버전으로 정렬한다:
--          flyway -baselineVersion=20260617.01 -baselineDescription="core schema baseline" baseline
--      (또는 SPRING_FLYWAY_BASELINE_VERSION=20260617.01 로 기동)
--   3) 이후 애플리케이션을 prod 프로파일(ddl-auto=validate)로 기동하면 검증을 통과하고,
--      신규 마이그레이션만 적용된다.
--
-- [재오픈 전 필수 리허설]
--   위 시나리오 B 를 운영과 동일한 빈 PostgreSQL 에서 1회 리허설하여, 마이그레이션 전체가
--   처음부터 끝까지 성공하고 앱이 validate 를 통과하는지 반드시 확인하라.
-- =====================================================================================

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    nickname    VARCHAR(255),
    grade       INTEGER,
    major       VARCHAR(255),
    status      VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    deleted_at  TIMESTAMP,
    created_at  TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS subjects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code   VARCHAR(32),
    semester      VARCHAR(20),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    subject_name  VARCHAR(255) NOT NULL,
    credits       INTEGER NOT NULL,
    professor     VARCHAR(255) NOT NULL,
    is_night      BOOLEAN NOT NULL DEFAULT FALSE,
    subject_type  VARCHAR(255) NOT NULL,
    class_method  VARCHAR(255) NOT NULL,
    grade         INTEGER,
    department    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS schedules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id   BIGINT,
    day_of_week  VARCHAR(255),
    start_time   DOUBLE PRECISION,
    end_time     DOUBLE PRECISION,
    CONSTRAINT fk_schedules_subject FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

CREATE TABLE IF NOT EXISTS user_timetables (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    subject_id  BIGINT NOT NULL,
    semester    VARCHAR(255),
    added_at    TIMESTAMP,
    memo        VARCHAR(255),
    CONSTRAINT fk_user_timetables_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_timetables_subject FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

CREATE TABLE IF NOT EXISTS wishlist_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    subject_id   BIGINT NOT NULL,
    semester     VARCHAR(255),
    priority     INTEGER,
    is_required  BOOLEAN DEFAULT FALSE,
    added_at     TIMESTAMP,
    CONSTRAINT fk_wishlist_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishlist_items_subject FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

-- 자주 쓰이는 조회 인덱스 (성능용 — ddl-auto=validate 는 인덱스를 검증하지 않으므로 best-effort).
-- 유니크 인덱스(user_timetables / wishlist_items) 및 추가 인덱스는 db/migration 의 후속 마이그레이션이 생성한다.
CREATE INDEX IF NOT EXISTS idx_schedules_subject_id ON schedules (subject_id);
CREATE INDEX IF NOT EXISTS idx_user_timetables_user_id ON user_timetables (user_id);
CREATE INDEX IF NOT EXISTS idx_user_timetables_subject_id ON user_timetables (subject_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_items_user_id ON wishlist_items (user_id);

-- subjects 조회/필터 인덱스 (Subject 엔티티 @Table(indexes=...) 정의와 일치).
-- 신규 DB(시나리오 B)에서 이 인덱스가 없으면 과목 필터/검색이 전체 테이블 스캔으로 동작한다.
CREATE INDEX IF NOT EXISTS idx_subject_name ON subjects (subject_name);
CREATE INDEX IF NOT EXISTS idx_subject_course_code ON subjects (course_code);
CREATE INDEX IF NOT EXISTS idx_subject_semester_active ON subjects (semester, active);
CREATE INDEX IF NOT EXISTS idx_professor ON subjects (professor);
CREATE INDEX IF NOT EXISTS idx_department ON subjects (department);
CREATE INDEX IF NOT EXISTS idx_grade ON subjects (grade);
CREATE INDEX IF NOT EXISTS idx_subject_type ON subjects (subject_type);
CREATE INDEX IF NOT EXISTS idx_is_night ON subjects (is_night);
CREATE INDEX IF NOT EXISTS idx_search_filter ON subjects (subject_name, grade, department);
