ALTER TABLE users
    ADD COLUMN IF NOT EXISTS status VARCHAR(20);

UPDATE users
SET status = 'ACTIVE'
WHERE status IS NULL;

ALTER TABLE users
    ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE users
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
