-- 자체 제품 분석용 사용자 행동 이벤트 로그.
-- 로그 성격이라 users FK 없이 user_id(nullable)만 둔다(비로그인 허용 + 대량 삽입).
CREATE TABLE IF NOT EXISTS analytics_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(40) NOT NULL,
    user_id     BIGINT,
    label       VARCHAR(255),
    session_id  VARCHAR(64),
    occurred_at TIMESTAMP NOT NULL
);

-- 이벤트타입별 + 기간 집계, 일별 집계를 커버하는 인덱스.
CREATE INDEX IF NOT EXISTS idx_analytics_events_type_time ON analytics_events (event_type, occurred_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_occurred ON analytics_events (occurred_at);
